# Generated by Django 5.0.4 on 2024-04-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_img",
            field=models.ImageField(blank=True, null=True, upload_to="profile_images/"),
        ),
    ]
