# Generated by Django 5.0.4 on 2024-04-18 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name="learningcontent",
            name="level",
        ),
        migrations.RemoveField(
            model_name="userprogress",
            name="content",
        ),
        migrations.RemoveField(
            model_name="userprogress",
            name="user",
        ),
        migrations.DeleteModel(
            name="CEFRLevel",
        ),
        migrations.DeleteModel(
            name="LearningContent",
        ),
        migrations.DeleteModel(
            name="UserProgress",
        ),
    ]
