# Generated by Django 5.0.4 on 2024-04-19 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_chat_remove_learningcontent_level_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Chat",
        ),
    ]
